config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  get 'welcome/index'

  resources :cost_centers
  resources :movement_states
  resources :movement_types
  resources :categories
  resources :account_movements
  resources :companies
  devise_for :users

  authenticated :user do
    devise_scope :user do
      root to: "dashboard#index"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "welcome#index", :as => "unauthenticated"
    end
  end

  
  use_doorkeeper # doorkeeper
  mount API::Root => '/'
  #mount API::Base => '/api' # Grape

resources :documentation, only: [:index] do # swagger-ui
  collection do # documentation token redirect
    get :o2c
    get :authorize
  end
end


end

app/models/movement_state.rb
class MovementState < ActiveRecord::Base
  belongs_to :company
  has_many :account_movements

  def self.company_movement_states company
    # Returns a Hash
    movement_states = company.movement_states
    movement_states.map do |a|
      inputs = AccountMovement.element_incomes(a)
      outputs = AccountMovement.element_outputs(a)
      summary_in = SummaryGen.new(inputs)
      summary_out = SummaryGen.new(outputs)

      total_in_out = ((t = summary_in.total) ? t : 0) - ((t = summary_out.total) ? t : 0)
      {id: a.id, name: a.name, total_items: (inputs.size + outputs.size), 
        total_in_out: total_in_out}
    end
  end
end

app/controllers/movement_states_controller.rb
class MovementStatesController < ApplicationController
  before_action :set_movement_state, only: [:show, :edit, :update, :destroy]

  # GET /movement_states
  # GET /movement_states.json
  def index
    @movement_states = MovementState.company_movement_states(@company)
  end

  # GET /movement_states/1
  # GET /movement_states/1.json
  def show
  end

  # GET /movement_states/new
  def new
    @movement_state = @company.movement_states.new
  end

  # GET /movement_states/1/edit
  def edit
  end

  # POST /movement_states
  # POST /movement_states.json
  def create
    @movement_state = @company.movement_states.new(movement_state_params)

    respond_to do |format|
      if @movement_state.save
        format.html { redirect_to @movement_state, notice: 'Movement state was successfully created.' }
        format.json { render :show, status: :created, location: @movement_state }
      else
        format.html { render :new }
        format.json { render json: @movement_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movement_states/1
  # PATCH/PUT /movement_states/1.json
  def update
    respond_to do |format|
      if @movement_state.update(movement_state_params)
        format.html { redirect_to @movement_state, notice: 'Movement state was successfully updated.' }
        format.json { render :show, status: :ok, location: @movement_state }
      else
        format.html { render :edit }
        format.json { render json: @movement_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movement_states/1
  # DELETE /movement_states/1.json
  def destroy
    @movement_state.destroy
    respond_to do |format|
      format.html { redirect_to movement_states_url, notice: 'Movement state was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_movement_state
      @movement_state = MovementState.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movement_state_params
      params.require(:movement_state).permit(:name, :company_id)
    end
end

app/helpers/movement_states_helper.rb
module MovementStatesHelper
end

app/views/movement_states/_form.html.erb
<%= form_for(@movement_state) do |f| %>
  <% if @movement_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movement_state.errors.count, "error") %> prohibited this movement_state from being saved:</h2>

      <ul>
      <% @movement_state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movement_states/edit.html.erb
<h1>Editing Movement State</h1>

<%= render 'form' %>

<%= link_to 'Show', @movement_state %> |
<%= link_to 'Back', movement_states_path %>

app/views/movement_states/index.html.erb
<div class="container-fluid">
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Movement States <small>Listing</small>
        </h1>
    </div>
</div>

<!-- Action Bar -->
<div class="row">
  <div class="col-lg-12">
    <div class="btn-group btn-group-justified action-group" role="group" aria-label="...">
      <div class="btn-group" role="group">
        <%= link_to 'New Movement state', new_movement_state_path, class:"btn btn-default" %>
      </div>
      <div class="btn-group" role="group">
        <%= link_to 'Movement States Report', '#', class:"btn btn-default" %>
      </div>
    </div>
  </div>
</div>

<!-- General Info -->
<p class="lead">
Almost every payment passes through a series of steps. Movement States handle these, with this you can monitor each movement through its life cyle.</p>

<!-- Main Page Content -->
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Total Items</th>
      <th>Pay/Recieve</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movement_states.each do |movement_state| %>
      <tr>
        <td><%= movement_state[:name] %></td>
        <td><%= movement_state[:total_items] %></td>
        <td><%= movement_state[:total_in_out] %></td>
        <td><%= link_to 'Show', movement_state_path(movement_state[:id]) %></td>
        <td><%= link_to 'Edit', edit_movement_state_path(movement_state[:id]) %></td>
        <td><%= link_to 'Destroy', movement_state_path(movement_state[:id]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div></div></div><!-- ./Row -->

</div><!-- ./Container fluid -->

app/views/movement_states/new.html.erb
<h1>New Movement State</h1>

<%= render 'form' %>

<%= link_to 'Back', movement_states_path %>

app/views/movement_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movement_state.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @movement_state.company_id %>
</p>

<%= link_to 'Edit', edit_movement_state_path(@movement_state) %> |
<%= link_to 'Back', movement_states_path %>