config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  get 'welcome/index'

  resources :cost_centers
  resources :movement_states
  resources :movement_types
  resources :categories
  resources :account_movements
  resources :companies
  devise_for :users

  authenticated :user do
    devise_scope :user do
      root to: "dashboard#index"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "welcome#index", :as => "unauthenticated"
    end
  end

  
  use_doorkeeper # doorkeeper
  mount API::Root => '/'
  #mount API::Base => '/api' # Grape

resources :documentation, only: [:index] do # swagger-ui
  collection do # documentation token redirect
    get :o2c
    get :authorize
  end
end


end

app/controllers/movement_types_controller.rb
class MovementTypesController < ApplicationController
  before_action :set_movement_type, only: [:show, :edit, :update, :destroy]

  # GET /movement_types
  # GET /movement_types.json
  def index
    @movement_types = MovementType.company_movement_types(@company)
  end

  # GET /movement_types/1
  # GET /movement_types/1.json
  def show
  end

  # GET /movement_types/new
  def new
    @movement_type = @company.movement_types.new
  end

  # GET /movement_types/1/edit
  def edit
  end

  # POST /movement_types
  # POST /movement_types.json
  def create
    @movement_type = @company.movement_types.new(movement_type_params)

    respond_to do |format|
      if @movement_type.save
        format.html { redirect_to @movement_type, notice: 'Movement type was successfully created.' }
        format.json { render :show, status: :created, location: @movement_type }
      else
        format.html { render :new }
        format.json { render json: @movement_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movement_types/1
  # PATCH/PUT /movement_types/1.json
  def update
    respond_to do |format|
      if @movement_type.update(movement_type_params)
        format.html { redirect_to @movement_type, notice: 'Movement type was successfully updated.' }
        format.json { render :show, status: :ok, location: @movement_type }
      else
        format.html { render :edit }
        format.json { render json: @movement_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movement_types/1
  # DELETE /movement_types/1.json
  def destroy
    @movement_type.destroy
    respond_to do |format|
      format.html { redirect_to movement_types_url, notice: 'Movement type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_movement_type
      @movement_type = MovementType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movement_type_params
      params.require(:movement_type).permit(:name, :company_id)
    end
end

app/helpers/movement_types_helper.rb
module MovementTypesHelper
end

app/views/movement_types/_form.html.erb
<%= form_for(@movement_type) do |f| %>
  <% if @movement_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movement_type.errors.count, "error") %> prohibited this movement_type from being saved:</h2>

      <ul>
      <% @movement_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.number_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movement_types/edit.html.erb
<h1>Editing Movement Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @movement_type %> |
<%= link_to 'Back', movement_types_path %>

app/views/movement_types/index.html.erb
<div class="container-fluid">

<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">
          Movement Types <small>Listing</small>
      </h1>
  </div>
</div>

<!-- Action Bar -->
<div class="row">
  <div class="col-lg-12">
    <div class="btn-group btn-group-justified action-group" role="group" aria-label="...">
      <div class="btn-group" role="group">
        <%= link_to 'New Movement type', new_movement_type_path, class:"btn btn-default" %>
      </div>
      <div class="btn-group" role="group">
        <%= link_to 'Movement Types Report', '#', class:"btn btn-default" %>
      </div>
    </div>
  </div>
</div>

<!-- General Info -->
<p class="lead">
For an easy explanation the most common movement types are fixed and variable income/expence. In this page you can create your own types. Types are mostly asociated with the fecuency of some movement.</p>


<!-- Main Page Content -->
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Total Items</th>
      <th>Total Income</th>
      <th>Total Expense</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movement_types.each do |movement_type| %>
      <tr>
        <td><%= movement_type[:name] %></td>
        <td><%= movement_type[:total_items] %></td>
        <td><%= movement_type[:total_in] %></td>
        <td><%= movement_type[:total_out] %></td>
        <td><%= link_to 'Show', movement_type_path(movement_type[:id]) %></td>
        <td><%= link_to 'Edit', edit_movement_type_path(movement_type[:id]) %></td>
        <td><%= link_to 'Destroy', movement_type_path(movement_type[:id]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div></div></div><!-- ./Row -->

</div><!-- ./Container fluid -->

app/views/movement_types/new.html.erb
<h1>New Movement Type</h1>

<%= render 'form' %>

<%= link_to 'Back', movement_types_path %>

app/views/movement_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movement_type.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @movement_type.company_id %>
</p>

<%= link_to 'Edit', edit_movement_type_path(@movement_type) %> |
<%= link_to 'Back', movement_types_path %>