config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  get 'welcome/index'

  resources :cost_centers
  resources :movement_states
  resources :movement_types
  resources :categories
  resources :account_movements
  resources :companies
  devise_for :users

  authenticated :user do
    devise_scope :user do
      root to: "dashboard#index"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "welcome#index", :as => "unauthenticated"
    end
  end

  
  use_doorkeeper # doorkeeper
  mount API::Root => '/'
  #mount API::Base => '/api' # Grape

resources :documentation, only: [:index] do # swagger-ui
  collection do # documentation token redirect
    get :o2c
    get :authorize
  end
end


end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :company
  has_many :account_movements

  def self.company_categories company
    # Returns a Hash
    categories = company.categories
    categories.map do |a|
      inputs = AccountMovement.element_incomes(a)
      outputs = AccountMovement.element_outputs(a)
      summary_in = SummaryGen.new(inputs)
      summary_out = SummaryGen.new(outputs)

      {id: a.id, name: a.name, total_items: (inputs.size + outputs.size), 
        total_in: summary_in.total, total_out: summary_out.total}
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.company_categories(@company)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = @company.categories.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = @company.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :company_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container-fluid">
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Categories <small>Listing</small>
        </h1>
    </div>
</div>

<!-- Action Bar -->
<div class="row">
  <div class="col-lg-12">
    <div class="btn-group btn-group-justified action-group" role="group" aria-label="...">
      <div class="btn-group" role="group">
        <%= link_to 'New Category', new_category_path, class:"btn btn-default" %>
      </div>
      <div class="btn-group" role="group">
        <%= link_to 'Categories Report', '#', class:"btn btn-default" %>
      </div>
    </div>
  </div>
</div>

<!-- General Info -->
<p class="lead">
Categories is just a way to classify different incomes or expences. They offer an aditional clasification system than Cost Centers.</p>

<!-- Main Page Content -->
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Total Items</th>
      <th>Total Income</th>
      <th>Total Expense</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category[:name] %></td>
        <td><%= category[:total_items] %></td>
        <td><%= category[:total_in] %></td>
        <td><%= category[:total_out] %></td>
        <td><%= link_to 'Show', category_path(category[:id]) %></td>
        <td><%= link_to 'Edit', edit_category_path(category[:id]) %></td>
        <td><%= link_to 'Destroy', category_path(category[:id]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div></div></div><!-- ./Row -->

</div><!-- ./Container fluid -->

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @category.company_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>