config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  get 'welcome/index'

  resources :cost_centers
  resources :movement_states
  resources :movement_types
  resources :categories
  resources :account_movements
  resources :companies
  devise_for :users

  authenticated :user do
    devise_scope :user do
      root to: "dashboard#index"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "welcome#index", :as => "unauthenticated"
    end
  end

  
  use_doorkeeper # doorkeeper
  mount API::Root => '/'
  #mount API::Base => '/api' # Grape

resources :documentation, only: [:index] do # swagger-ui
  collection do # documentation token redirect
    get :o2c
    get :authorize
  end
end


end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in" role="alert">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <%= link_to site_name, root_path, class: "navbar-brand" %>
  </div>

  <!-- Top Menu Items -->
  <% unless user_signed_in? %><!-- No one signed in -->

    <ul class="nav navbar-right top-nav">
      <li><%= button_to 'Sign up', registration_path(:user), class: "btn btn-default navbar-btn" %></li>
    </ul>

    <%= form_for(:user, :url => session_path(:user), html: {class: "navbar-form navbar-right"} ) do |f| %>
      <div class="form-group">
        <%= f.text_field :email,  placeholder: "Email", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
      </div>
      <%= f.submit 'Sign in', class: "btn btn-success" %>
    <% end %><!-- ./form -->

  <% else %><!-- Client signed in -->
    <ul class="nav navbar-right top-nav">
      <li><p class="navbar-text">Signed in as <a href="#" class="navbar-link"><%= current_user.email %></a></p></li>
      <li><%= button_to 'Sign out', destroy_session_path(:user), method: :delete, class: "btn btn-default navbar-btn" %></li>
    </ul>
    <%= render 'layouts/sidebar'%>
  <% end %>
</nav>


            

app/views/layouts/_sidebar.html.erb
<div class="navbar-collapse navbar-ex1-collapse collapse" aria-expanded="false" style="height: 1px;">
    <ul class="nav navbar-nav side-nav">
        <li <%= nav_active root_path %> >
            <a href="<%= root_path %>"><i class="fa fa-dashboard"></i> <%= t(:dashboard) %></a>
        </li>
        <li <%= nav_active account_movements_path %> >
            <a href="<%= account_movements_path %>"><i class="fa fa-money"></i> <%= t(:account_movements) %></a>
        </li>
        <li <%= nav_active cost_centers_path %> >
            <%= link_to t(:cost_centers), cost_centers_path %>
        </li>
        <li <%= nav_active movement_states_path %> >
            <%= link_to t(:movement_states), movement_states_path %>
        </li>
        <li <%= nav_active categories_path %> >
            <%= link_to t(:categories), categories_path %>
        </li>
        <li <%= nav_active movement_types_path %> >
            <%= link_to t(:movement_types), movement_types_path %>
        </li>
        <li <%= nav_active companies_path %> >
            <%= link_to t(:company), companies_path %>
        </li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= site_name %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
		<% unless current_user %>
			<!-- Navigation -->
			<%= render 'layouts/nav_bar' %>
		    <%= render partial: "layouts/flash_messages", flash: flash %> 
			<%= yield %>
		<% else %>
			<div id="wrapper">
				<!-- Navigation -->
				<%= render 'layouts/nav_bar' %>
				<div id="page-wrapper">
					<%= render partial: "layouts/flash_messages", flash: flash %> 
					<%= yield %>
			 	</div>
		 	</div>
		<% end %>
</body>
</html>